name: CI

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-alpha*
      - v[0-9]+.[0-9]+.[0-9]+-beta*
      - v[0-9]+.[0-9]+.[0-9]+-rc*

jobs:
  build:
    name: Build Bundle
    runs-on: ubuntu-20.04
    steps:

      - name: Set build mode
        id: build-mode
        run: |
          BUILD_MODE='production'
          if [[ "${GITHUB_REF}" =~ "alpha" ]]; then
              BUILD_MODE='development'
          elif [[ "${GITHUB_REF}" =~ "beta" ]]; then
              BUILD_MODE='development'
          fi
          echo "Build mode: ${BUILD_MODE}"
          echo "::set-output  name=BUILD_MODE::${BUILD_MODE}"

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Production Bundle with Webpack
        if: ${{ steps.build-mode.outputs.BUILD_MODE == 'production' }}
        run: npm run build

      - name: Development Bundle with Webpack
        if: ${{ steps.build-mode.outputs.BUILD_MODE == 'development' }}
        run: npm run build:dev

      - name: Generate version string
        id: version-string
        run: echo "::set-output name=VERSION_STR::${GITHUB_REF##*/}"

      - name: Get version number
        id: version-number
        run: echo "::set-output name=VERSION_NUM::${GITHUB_REF:11}"

      - name: Create Production ZIP file with version
        if: ${{ steps.build-mode.outputs.BUILD_MODE == 'production' }}
        run: |
          zip -r fv-bundle-${{ steps.version-number.outputs.VERSION_NUM }}.zip dist
          ls -l | grep .zip

      - name: Create Development ZIP file with version
        if: ${{ steps.build-mode.outputs.BUILD_MODE == 'development' }}
        run: |
          zip -r fv-bundle-${{ steps.version-number.outputs.VERSION_NUM }}.zip build
          ls -l | grep .zip

      - name: Release Bundle
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: fv-bundle-${{ steps.version-number.outputs.VERSION_NUM }}.zip
          name: ${{ steps.version-string.outputs.VERSION_STR }}
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }}
          tag: ${{ steps.version-string.outputs.VERSION_STR }}
          token: ${{ secrets.GITHUB_TOKEN }}
