
name: CI

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-alpha*
      - v[0-9]+.[0-9]+.[0-9]+-beta*

jobs:
  build:
    name: Build Bundle
    runs-on: ubuntu-20.04
    steps:

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Bundle with Webpack
        run: npm run build

      - name: Generate version string
        id: version-string
        run: echo "::set-output name=VERSION_STR::${GITHUB_REF##*/}"

      - name: Get version number
        id: version-number
        run: echo "::set-output name=VERSION_NUM::${GITHUB_REF:11}"

      - name: Create ZIP file with version
        run: |
          zip -r fv_bundle_${{ steps.version-number.outputs.VERSION_NUM }}.zip dist
          ls -l | grep .zip

      - name: Release Bundle
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: fv_bundle_${{ steps.version-number.outputs.VERSION_NUM }}.zip
          name: Release ${{ steps.version-string.outputs.VERSION_STR }}
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') }}
          tag: ${{ steps.version-string.outputs.VERSION_STR }}
          token: ${{ secrets.GITHUB_TOKEN }}
